# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_kotelnikov', '0002_auto_20170307_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='ask_kotelnikov.Tag'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ask_kotelnikov.UserProfile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(null=True, to='ask_kotelnikov.Answer'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='uploads/', verbose_name='Images'),
        ),
    ]
