# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_kotelnikov', '0003_auto_20170309_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ask_kotelnikov.Answer'),
        ),
    ]
