# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_kotelnikov', '0004_auto_20170309_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ask_kotelnikov.Answer'),
        ),
    ]
