# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_kotelnikov', '0007_auto_20170309_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='question',
            name='user_that_makes_it',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ask_kotelnikov.UserProfile'),
        ),
        migrations.AddField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(related_name='tags', to='ask_kotelnikov.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_kotelnikov.UserProfile'),
        ),
    ]
